name: build and test
on: push

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        python-version: ["3.12"]
        poetry-version: ["1.7.1"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
          
      - name: View poetry --help
        run: poetry --help

      - name: Check formatting using Black
        run: poetry run black . --check

      - name: Run unit tests
        run: poetry run python -m unittest discover tests

      - name: Run Mypy
        run: poetry run mypy ray_tracer_challenge

      - name: Run Pylint
        run: poetry run pylint ray_tracer_challenge
